basePath: /api/v1
definitions:
  handlers.userResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      role:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  models.Film:
    properties:
      age_rating:
        type: string
      duration:
        type: integer
      genres:
        items:
          $ref: '#/definitions/models.Genre'
        type: array
      id:
        type: integer
      poster_url:
        type: string
      release_year:
        type: integer
      synopsis:
        type: string
      title:
        type: string
    type: object
  models.FilmRequest:
    properties:
      age_rating:
        example: 16+
        type: string
      duration:
        example: 114
        type: integer
      genre_ids:
        example:
        - 1
        - 3
        items:
          type: integer
        type: array
      release_year:
        example: 2026
        type: integer
      synopsis:
        example: Ghostface is back in town...
        type: string
      title:
        example: Scream 7
        type: string
    type: object
  models.Genre:
    properties:
      genre_name:
        example: Action
        type: string
      id:
        example: 1
        type: integer
    type: object
  models.GenreRequest:
    properties:
      genre_name:
        example: Action
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      role:
        description: 'enum: "user" atau "admin"'
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: API backend untuk aplikasi pemesanan tiket bioskop
  title: Ticketing API
  version: "1.0"
paths:
  /film:
    get:
      consumes:
      - application/json
      description: Mengembalikan seluruh daftar film beserta genrenya
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Film'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Ambil semua data film
      tags:
      - Film
    post:
      consumes:
      - application/json
      description: Menambahkan data film baru beserta genrenya (khusus admin)
      parameters:
      - description: Data film
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.FilmRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Film'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Buat film baru
      tags:
      - Film
  /film/{id}:
    delete:
      description: Menghapus data film berdasarkan ID (khusus admin)
      parameters:
      - description: Film ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Hapus film
      tags:
      - Film
    get:
      consumes:
      - application/json
      description: Mengembalikan detail satu film beserta genrenya
      parameters:
      - description: Film ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Film'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Ambil data film berdasarkan ID
      tags:
      - Film
    patch:
      consumes:
      - application/json
      description: Memperbarui data film dan relasi genrenya (khusus admin)
      parameters:
      - description: Film ID
        in: path
        name: id
        required: true
        type: integer
      - description: Data film
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.FilmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Film'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update film
      tags:
      - Film
  /film/{id}/poster:
    post:
      consumes:
      - multipart/form-data
      description: Mengupload file poster untuk film tertentu (khusus admin)
      parameters:
      - description: Film ID
        in: path
        name: id
        required: true
        type: integer
      - description: File Gambar
        in: formData
        name: poster
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Upload Poster Film
      tags:
      - Film
  /genre:
    get:
      description: Mengembalikan daftar seluruh genre film
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Genre'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Ambil semua genre
      tags:
      - Genre
    post:
      consumes:
      - application/json
      description: Menambahkan data genre baru ke dalam sistem
      parameters:
      - description: Data Genre
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.GenreRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Genre'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Tambah genre baru
      tags:
      - Genre
  /genre/{id}:
    delete:
      description: Menghapus genre berdasarkan ID
      parameters:
      - description: Genre ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Hapus genre
      tags:
      - Genre
    get:
      description: Mengembalikan detail satu genre
      parameters:
      - description: Genre ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Genre'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Ambil genre berdasarkan ID
      tags:
      - Genre
    patch:
      consumes:
      - application/json
      description: Mengubah nama genre berdasarkan ID
      parameters:
      - description: Genre ID
        in: path
        name: id
        required: true
        type: integer
      - description: Data Genre Baru
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.GenreRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Genre'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update genre
      tags:
      - Genre
  /login:
    post:
      consumes:
      - application/json
      description: Autentikasi user menggunakan email dan password untuk mendapatkan
        JWT token
      parameters:
      - description: Kredensial Login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User Login
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Mendaftarkan user baru ke sistem
      parameters:
      - description: Data Registrasi
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User Register
      tags:
      - Auth
  /user:
    get:
      description: Mengembalikan seluruh daftar user tanpa field password
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.userResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Ambil semua user
      tags:
      - User
  /user/{id}:
    delete:
      description: Menghapus user berdasarkan ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Hapus user
      tags:
      - User
    get:
      description: Mengembalikan detail user tanpa field password berdasarkan ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.userResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Ambil user berdasarkan ID
      tags:
      - User
    patch:
      consumes:
      - application/json
      description: Mengubah data user berdasarkan ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Data user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.userResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update user
      tags:
      - User
securityDefinitions:
  BearerAuth:
    description: 'Masukkan token dengan format: Bearer <spasi> token-anda'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
